# Generated by Django 5.1.4 on 2025-02-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0004_rename_login_data_login_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('message', models.CharField(max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='register_view',
            name='cpass',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='register_view',
            name='email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='register_view',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
