# Generated by Django 5.1.4 on 2025-03-18 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0006_booking_review'),
        ('Audio', '0022_booking'),
    ]

    operations = [
    ]
