# Generated by Django 5.1.4 on 2025-03-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0023_merge_0006_booking_review_0022_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Audio',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.AddField(
            model_name='booking',
            name='mobile',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
