# Generated by Django 5.1.4 on 2025-03-18 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0024_add_mobile_to_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='mobile',
            new_name='phone_number',
        ),
    ]
