# Generated by Django 5.1.4 on 2025-03-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0027_booking_guide_name_booking_status_booking_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='emergency_contact1',
            field=models.CharField(blank=True, help_text='Emergency contact number 1', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='emergency_contact2',
            field=models.CharField(blank=True, help_text='Emergency contact number 2', max_length=15, null=True),
        ),
    ]
