# Generated by Django 5.1.4 on 2025-03-18 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0028_booking_emergency_contact1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='emergency_contact1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='emergency_contact2',
        ),
    ]
