# Generated by Django 5.1.4 on 2025-03-19 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Audio', '0030_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
