from django.urls import path
from Audio import views

urlpatterns = [
    # path('',views.login,name='login'),
    path('register/',views.register,name='register'),
    path('login/',views.user_login,name='login'),
    path('',views.index,name='index'),
    path('home/',views.home,name='home'),
    path('profilepage/',views.profile_page,name='profile_page'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('tour/',views.tour,name='tour'),
    path('tour-detail1/',views.tourdetail1,name='tour-detail1'),
    path('tour-detail2/',views.tourdetail2,name='tour-detail2'),
    path('tour-detail3/',views.tourdetail3,name='tour-detail3'),
    path('tour-detail4/',views.tourdetail4,name='tour-detail4'),
    path('tour-detail5/',views.tourdetail5,name='tour-detail5'),
    path('tour-detail6/',views.tourdetail6,name='tour-detail6'),
    path('tour-detail7/',views.tourdetail7,name='tour-detail7'),
    path('tour-detail8/',views.tourdetail8,name='tour-detail8'),
    path('tour-detail9/',views.tourdetail9,name='tour-detail9'),
    path('tour-detail10/',views.tourdetail10,name='tour-detail10'),
    path('Audio1/',views.Audio1,name='Audio1'),
    path('Audio2/',views.Audio2,name='Audio2'),
    path('Audio3/',views.Audio3,name='Audio3'),
    path('Audio4/',views.Audio4,name='Audio4'),
    path('Audio5/',views.Audio5,name='Audio5'),
    path('Audio6/',views.Audio6,name='Audio6'),
    path('Audio7/',views.Audio7,name='Audio7'),
    path('Audio8/',views.Audio8,name='Audio8'),
    path('Audio9/',views.Audio9,name='Audio9'),
    path('Audio10/',views.Audio10,name='Audio10'),
    path('bookguide/',views.bookguide,name='bookguide'),
    path('bookguide/<str:guide_name>/<str:guide_place>/',views.bookguide,name='bookguide'),
    path('otp/',views.otp,name='otp'),
    path('verify_otp/',views.verify_otp,name='verify_otp'),
    path('confirmation/',views.confirmation,name='confirmation'),
    path('contact/',views.contact,name='contact'),
    path('logout/',views.logout,name='logout'),
    path('ahmedabad/',views.ahmedabad,name='ahmedabad'),
    path('cancel_booking/<int:booking_id>/', views.cancel_booking, name='cancel_booking'),
    # path('header/',views.header,name='header'),
]